// <auto-generated />
namespace Detergente.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ForeingKey_FamiliaArticulo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForeingKey_FamiliaArticulo));
        
        string IMigrationMetadata.Id
        {
            get { return "201803010549074_ForeingKey_FamiliaArticulo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
