// <auto-generated />
namespace Detergente.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _01032018_4_57_RodrigoB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01032018_4_57_RodrigoB));
        
        string IMigrationMetadata.Id
        {
            get { return "201803010808176_01032018_4_57_RodrigoB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
