// <auto-generated />
namespace Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class newTablasDetalleCarrito_Direccion_Pedido : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newTablasDetalleCarrito_Direccion_Pedido));
        
        string IMigrationMetadata.Id
        {
            get { return "201803130258014_newTablasDetalleCarrito_Direccion_Pedido"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
